name: anphuc-copilot

services:
  db:
    container_name: pgvector-db
    image: ankane/pgvector
    restart: unless-stopped
    ports:
      - 54321:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=123
      - PGADMIN_CONFIG_LOGIN_BANNER="Use user@domain.com and 123 login"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data

  app:
    container_name: anphuc-copilot
    # image: phucnguyen/anphuc-copilot:latest
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/db?schema=public}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
  pgadmin-data:
  seq-data:
